services:
        webserver:
                build:
                        context: ./app
                        dockerfile: static.Dockerfile
                ports:
                        - 8080:80
                container_name: static_website
                volumes:
                        - ./app:/usr/share/nginx/html/